### ISSUE TITLE
Document required for DSR dataset annotation

### ISSUE THREAD

**Issue by cilliankieran** [ethyca/fidesdocs#105]
### DSR dataset annotation document

We require a single page document describing the process to annotate a dataset representing a general database for DSR automation.

## Page Requirements
The guide should include:
1. Summary (1 - 2 lines) of what the document explains and what you'll learn.
2. Prerequisites to dataset annotation.
3. Key of terms and annotation labels.
4. Examples for each major annotation convention with an explanation of its purpose/use
5. Short sample dataset that shows all of the annotation conventions

## Branch / Page Location
For this work please use the `06082023-ck-doc-updates` branch and use the page located at:
`pages / tutorials / privacy-requests-dataset-annotation.mdx`

**Comment by rsilvery** [comment]
I just did this and it's been published to docs under User Guides > Dataset > annotate datasets
