### ISSUE TITLE
Broken Image in Consent Tutorial

### ISSUE THREAD

**Issue by suchiroll** [ethyca/fidesdocs#239]
### Docs Update Description

Broken image in Consent Tutorial, data use for consent
/assets/img/tutorials/data-mapping-data-use-system-portal.gif doesn't exist

Describe the related work: Fix URL or add image- not sure what's the correct gif for this

Related links: https://docs.ethyca.com/tutorials/consent-management-configuration/data-use-for-consent

**Comment by rsilvery** [comment]
@suchiroll  please file in DOX board.
