### ISSUE TITLE
Update ERD Diagram for `fides==2.5.0`

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fidesdocs#34]
### Docs Update Description

Describe the problem: The ERD Diagram will be out of date once `2.5.0` is released for `fides`

Describe the purpose: The ERD Diagram should be up to date

Describe the related work: Replace `img/app_database.png` with the new file

Related links: [fides==2.5.0](https://github.com/ethyca/fides/pull/2295)

### Additional context

![app_database](https://user-images.githubusercontent.com/6758661/213592931-7067f8a2-73fc-4268-8e71-d6f839cbf5e9.png)

**Comment by SteveDMurphy** [comment]
Thank you @suchiroll !!

**Comment by suchiroll** [comment]
hey hey @SteveDMurphy i'm taking a look at this now, do you know where in the docs this should be? doesn't look like it's in the current docs post the unified fides rewrite?

**Comment by SteveDMurphy** [comment]
> hey hey @SteveDMurphy i'm taking a look at this now, do you know where in the docs this should be? doesn't look like it's in the current docs post the unified fides rewrite?

So I completely missed your comment here @suchiroll - my bad!! @chriscalhoun1974 is opening another issue for `2.6.0` now and maybe we can prioritize that one to decide a) if we still want/need to do this and if so b) where this should go to be in the new docs site
