### ISSUE TITLE
Visited links are unreadable in the search when not hovering

### ISSUE THREAD

**Issue by sanders41** [ethyca/fidesdocs#43]
### Docs Update Description

Describe the problem: When preforming a search, links that have been visited are very close to the same color as the background so very hard to read.

#### no hover

<img width="566" alt="Screenshot 2023-01-27 at 1 08 01 PM" src="https://user-images.githubusercontent.com/25045024/215162546-4071f70d-8c15-438d-929c-3695ad48aad0.png">

#### hover

<img width="574" alt="Screenshot 2023-01-27 at 1 08 11 PM" src="https://user-images.githubusercontent.com/25045024/215162650-f84bb0dc-4599-4cf2-a9b1-46960de45a2d.png">

Describe the purpose: _What needs to happen?_

Describe the related work: _Brief summary of any related engineering tickets, features, etc._

Related links: _Engineering tickets, PRs, Figma specs, current docs pages, etc._

### Additional context

_Add any other context about the problem here._

**Comment by rsilvery** [comment]
@suchiroll test
