### ISSUE TITLE
Titles are not displayed in code snippets

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fidesdocs#49]
### Docs Update Description

Code snippet title blocks (e.g the `json title="<code>PUT {host}/api/v1/storage/{request_id}</code>"` after the ``` to start a snippet) are not displaying the data inside `title="..."` atop the snippet. We need the URLs to show in order for the docs to be usable — I suspect this could be an issue in the styling?

**Comment by suchiroll** [comment]
hey @seanpreston could you link me to where this broken or provide a screenshot? 

for more context, Nextra uses 'Shiki' to style syntax which may differ  from the syntax we were using prior

more info can be found here: https://nextra.site/docs/guide/syntax-highlighting
