### ISSUE TITLE
Hide Colorado and CT regulation links

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fidesdocs#89]
<img width="1440" alt="Screenshot 2023-04-18 at 11 44 44 AM" src="https://user-images.githubusercontent.com/4807009/232835052-52a09f85-6d4d-4001-8fc6-41b1ba8fa370.png">

On the screenshot above the links for Colorado and CT are broken. Can we hide those blocks for the time being

**Comment by daveqnet** [comment]
I actually created a PR for this last month but never merged it!

https://github.com/ethyca/fidesdocs/pull/73

Happy to merge after the nextra bug is fixed.

**Comment by daveqnet** [comment]
Here's what it looks like in the PR branch deploy: https://fidesdocs-ncymn96il-ethyca.vercel.app/regulations/overview
